#!/usr/bin/env bash
#bash script that print bad luck in 4 good luck 8 and best school otherwise
i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done	
