#!/usr/bin/env bash
#script that print bad luck for china in 4 japan 9 and italy 17

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17")echo "bad luck from Italy";;
	esac
	(( i++ ))
done	
