#!/usr/bin/env bash
#script to fix the given container so that Nginx is running as the nginx user.

sed -i "s/#user www-data/user nginx" /etc/nginx/nginx.config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.config

sudo -u nginx service restart
